---
title: "Capstone_draft"
author: "Qinyun (Claire) Cai"
date: "2023-03-29"
output: html_document
---

```{r}
rm(list=ls())
cat("\014")

```

```{r}
# load packages needed 
library(sqldf)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(forecast)
library(caret)
library(pROC)
```

1. Data Pre-processing 

```{r}
#read data frame 
spot_df <- read.csv("Spot Data.csv")
```

```{r}
# change names with out dot

names(spot_df) <- c('Patient_ID','Patient_Zip','Patient_Age','Patient_Sex','Type_of_Kit',"Specimen_Type","Client_ID", "Datetime_Kit_Delivered","Datetime_Kit_Registered","Datetime_Sample_Sent_In","Datetime_Sample_Received","Datetime_of_End_Status","End_Status","Rejection_Reason")

```


```{r}
#check general duplication
duplicated_rows <- duplicated(spot_df)
duplicated_rows <- spot_df[duplicated_rows,]

#remove exactly same rows 
spot_df_unique <- unique(spot_df)


#check same patient duplication
#duplicated_patient <- duplicated(spot_df$Patient.ID)
#duplicated_patient <- spot_df[duplicated_patient,]


```

```{r}
# only keep rows with end_status are rejected, resulted and partially_resulted (for analyzing purpose)
spot_df_new <- subset(spot_df_unique, End_Status == "rejected" | End_Status == "resulted" | End_Status == "partially_resulted")

```

```{r}
# convert end status variable into dummy
new1 <- spot_df_new
new1$End_Status <- ifelse(new1$End_Status == "resulted", 1, 0)
```


```{r calculate End_Status rate}
# calculate resulted rate for who purchased same test kit 
result_rates <- new1 %>%
  group_by(Patient_ID,Type_of_Kit) %>%
  summarize(result_rates = mean(End_Status))

# merge the rate back as a new variable in the df called "result_rates"
df_with_result_rates <- left_join(result_rates, new1, by = c("Patient_ID", "Type_of_Kit"))



```



* visualization for time series

```{r df_time_variables - time series}
# select all time related variables to create a new df
df_time_variables <- new1 %>%
  select(Patient_ID,
         Datetime_Kit_Delivered,
         Datetime_Kit_Registered,
         Datetime_Sample_Sent_In,
         Datetime_Sample_Received,
         Datetime_of_End_Status,
         End_Status
         )

# convert all time-related variavles as date
df_time_variables$Datetime_Kit_Delivered <- as.Date(df_time_variables$Datetime_Kit_Delivered)
df_time_variables$Datetime_Kit_Registered <- as.Date(df_time_variables$Datetime_Kit_Registered)
df_time_variables$Datetime_Sample_Sent_In <- as.Date(df_time_variables$Datetime_Sample_Sent_In)
df_time_variables$Datetime_Sample_Received <- as.Date(df_time_variables$Datetime_Sample_Received)
df_time_variables$Datetime_of_End_Status <- as.Date(df_time_variables$Datetime_of_End_Status)

#remove NA
df_time_variables <- na.omit(df_time_variables)


```


```{r delivery time series daily}
kit_delivered <- df_time_variables %>% 
  group_by(day = as.Date(Datetime_Kit_Delivered)) %>% 
  summarise(kit_delivered_count = n())

plot(kit_delivered$day, kit_delivered$kit_delivered_count, type = "l", xlab = "Day", ylab = "Kit Delivered Count", main = "Daily Delivered Time Series")

top_day <- kit_delivered$day[which.max(kit_delivered$kit_delivered_count)]

abline(v = top_day, col = "red")

```

```{r Monthly Delivered Time Series}
#visual for kit delivered
kit_delivered <- df_time_variables %>% 
  group_by(month = lubridate::floor_date(Datetime_Kit_Delivered, "month")) %>% 
  summarise(kit_delivered_count = n())

plot(kit_delivered$month, kit_delivered$kit_delivered_count, type = "l", xlab = "Month", ylab = "Kit Delivered Count", main = "Monthly Delivered Time Series")

top_month <- kit_delivered$month[which.max(kit_delivered$kit_delivered_count)]

abline(v = top_month, col = "red")
```


```{r Monthly Registered Time Series}

#visual for kit registered
kit_registered <- df_time_variables %>% 
  group_by(month = lubridate::floor_date(Datetime_Kit_Registered, "month")) %>% 
  summarise(kit_registered_count = n())

plot(kit_registered$month, kit_registered$kit_registered_count, type = "l", xlab = "Month", ylab = "Kit Registered Count", main = "Monthly Registered Time Series")

top_month <- kit_registered$month[which.max(kit_registered$kit_registered_count)]

abline(v = top_month, col = "red")

```



```{r Monthly Sample sent in Time Series}


#visual for sample sent monthly
sample_sent_in <- df_time_variables %>% 
  group_by(month = lubridate::floor_date(Datetime_Sample_Sent_In, "month")) %>% 
  summarise(sample_sent_in_count = n())

plot(sample_sent_in$month, sample_sent_in$sample_sent_in_count, type = "l", xlab = "Month", ylab = "Sample Sent in", main = "Monthly Sample sent in Time Series")

top_month <- sample_sent_in$month[which.max(sample_sent_in$sample_sent_in_count)]

abline(v = top_month, col = "red")

```

```{r Monthly Sample Received Time Series}

#visual for sample received
sample_received <- df_time_variables %>% 
  group_by(month = lubridate::floor_date(Datetime_Sample_Received, "month")) %>% 
  summarise(sample_received_count = n())

plot(sample_received$month, sample_received$sample_received_count, type = "l", xlab = "Month", ylab = "Sample Received", main = "Monthly Sample Received Time Series")

top_month <- sample_received$month[which.max(sample_received$sample_received_count)]

abline(v = top_month, col = "red")

```

```{r Monthly End Status Released Time Series}
#visual for end status

end_status_time <- df_time_variables %>% 
  group_by(month = lubridate::floor_date(Datetime_of_End_Status, "month")) %>% 
  summarise(end_status_time_count = n())

plot(end_status_time$month, end_status_time$end_status_time_count, type = "l", xlab = "Month", ylab = "End Status Released", main = "Monthly End Status Released Time Series")

top_month <- end_status_time$month[which.max(end_status_time$end_status_time_count)]

abline(v = top_month, col = "red")
```


```{r ratios}
# we might want to know the registered rate, sample sent back rate, sample received rate 
library(dplyr)

ratios <- spot_df %>%
  summarize(
    registered_rate = n_distinct(Datetime_Kit_Registered) / n_distinct(Datetime_Kit_Delivered),
    sent_back_rate = n_distinct(Datetime_Sample_Sent_In) / n_distinct(Datetime_Kit_Registered)
  )

ratios



```

```{r}
new2 <- new1

# convert all time-related variavles as date
new2$Datetime_Kit_Delivered <- as.Date(new2$Datetime_Kit_Delivered)
new2$Datetime_Kit_Registered <- as.Date(new2$Datetime_Kit_Registered)
new2$Datetime_Sample_Sent_In <- as.Date(new2$Datetime_Sample_Sent_In)
new2$Datetime_Sample_Received <- as.Date(new2$Datetime_Sample_Received)
new2$Datetime_of_End_Status <- as.Date(new2$Datetime_of_End_Status)

#remove NA
new2 <- na.omit(new2)

```

```{r}
# calculate time gap

library(dplyr)

new2 <- new2 %>%
  mutate(
    sample_sent_back_days = as.numeric(difftime(Datetime_Sample_Sent_In, Datetime_Kit_Delivered, units = "days")),
    sample_received_days = as.numeric(difftime(Datetime_Sample_Received, Datetime_Sample_Sent_In, units = "days")),
    lab_process_days = as.numeric(difftime(Datetime_of_End_Status,Datetime_Sample_Received, units = "days"))
  )

#drop original time-related variables 
new2 <- new2 %>%
  select(-Datetime_Kit_Delivered,
         -Datetime_Kit_Registered,
         -Datetime_Sample_Sent_In,
         -Datetime_Sample_Received,
         -Datetime_of_End_Status)


```


```{r new 3 - processed data 1.0}
# drop variables that can not be put in model 

new3 <- new2 %>%
  select(-Patient_ID,
         -Patient_Zip,
         -Type_of_Kit,
         -Specimen_Type,
         -Client_ID)

# convert gender in to dummy, Female = 0, male = 1 
new3$Patient_Sex <- ifelse(new3$Patient_Sex == "M", 1, 0)

```


```{r}
#visual type of kits.
Type_of_Kit_Summary <- new2 %>%
  group_by(Type_of_Kit) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

g_type <- ggplot(Type_of_Kit_Summary, aes(x = Type_of_Kit, y= count)) +
  geom_bar(stat = "identity", fill = "#1f77b4") + 
  xlab("Type of Kit") +
  ylab("Count") +
  ggtitle("Count of Type of Kit by Category")

g_type

#--------------------------------------------------------
#visual type of kits and specimen type.
Specimen_Type_Summary <- new2 %>%
  group_by(Specimen_Type) %>%
  summarize(count = n()) %>%
  arrange(desc(count))

g_specimen <- ggplot(Specimen_Type_Summary, aes(x = Specimen_Type, y= count)) +
  geom_bar(stat = "identity", fill = "#1f77b4") + 
  xlab("Specimen Type") +
  ylab("Count") +
  ggtitle("Count of Specimen Type by Category")

g_specimen


```

new 4

```{r new 4 - processed data 2.0}
new4 <- new2

# convert gender in to dummy, Female = 0, male = 1 
new4$Patient_Sex <- ifelse(new4$Patient_Sex == "M", 1, 0)
new4$Type_of_Kit <- ifelse(new4$Type_of_Kit == "5805a410-5d6a-4df0-8f88-290710994672", 1, 0)
new4$Specimen_Type <- ifelse(new4$Specimen_Type == "adx100_2", 1, 0)

# remove zip code and IDs
new4 <- new4 %>%
  select(-Patient_ID,
         -Patient_Zip,
         -Client_ID,
         -Rejection_Reason)

```

```{r}
set.seed(231)
train.index <- sample(c(1:dim(new4)[1]), dim(new4)[1]*0.6)

train.df <- new4[train.index, ]
valid.df <- new4[-train.index, ]
```



```{r}
t(t(names(new4)))

logistic <- glm(End_Status~., data = train.df, family = binomial())

summary(logistic)

```

```{r}
prob_logistic <- predict(object=logistic, newdata = valid.df)

pred <- ifelse(prob_logistic>=0.9, "yes", "no")
pred <- factor(pred, levels = c("no", "yes"), order = TRUE)
f <- table(valid.df$End_Status, pred)
f


```
```{r}
prob_logistic_1 <- predict(object=logistic, valid.df, type = "response")
#prob_logistic_1
valid.df$predicted <- prob_logistic_1
confusionMatrix <- confusionMatrix(as.factor(valid.df$End_Status), 
                                   as.factor(ifelse(valid.df$predicted > 0.7, 1, 0)))
confusionMatrix


```
```{r}

confusionMatrix1 <- confusionMatrix(as.factor(valid.df$End_Status), 
                                   as.factor(ifelse(valid.df$predicted > 0.9, 1, 0)),
                                   mode = 'everything')

confusionMatrix1

```



```{r logit ROC}

roc_curve <- roc(valid.df$End_Status,prob_logistic_1)
names(roc_curve)
x <- 1-roc_curve$specificities
y <- roc_curve$sensitivities

library(ggplot2)
p <- ggplot(data = NULL, mapping = aes(x= x, y = y))
p + geom_line(colour = 'red') +geom_abline(intercept = 0, slope = 1) + 
  annotate('text', x = 0.4, y = 0.5, label =paste('AUC=',round(roc_curve$auc,2))) + 
  labs(x = '1-specificities',y = 'sensitivities', title = 'ROC Curve')

```










2. Data Visualization 


```{r}
# Patient Age Frequency Distribution 

# Create a small data frame including min, mode, median and max age.
annotations <- data.frame(
  x = c(round(min(spot_df_new$Patient_Age), 2), round(mean(spot_df_new$Patient_Age), 2), round(max(spot_df_new$Patient_Age), 2),names(table(spot_df_new$Patient_Age))[which.max(table(spot_df_new$Patient_Age))]),
  y = c(round(min(spot_df_new$Patient_Age), 2), round(mean(spot_df_new$Patient_Age), 2), round(max(spot_df_new$Patient_Age), 2),names(table(spot_df_new$Patient_Age))[which.max(table(spot_df_new$Patient_Age))]),
  label = c("Min", "Mean", "Max", "Mode")
) 

#view(annotations)


g1 <- ggplot(spot_df_new, aes(x=Patient_Age)) +
  geom_histogram(binwidth = 5, fill="#69b3a2", color="#e9ecef") +
  geom_vline(aes(xintercept = mean(Patient_Age)), linetype="dashed")+
  annotate("text", x=18, y=0, size =4, label = "Min:18")+
  annotate("text", x=33, y=1700, size =4, label = "Mode:33")+
  annotate("text", x=43.51, y=1450, size =4, label = "Mean:43.51")+
  annotate("text", x=88.00, y=0, size =4, label = "Max:88.00")+
  theme_bw()+
  labs(x="Patient Age", y="Count")
  

g1


```





```{r}
# convert end status as dummy variable, resulted = 1, rejected/partially_resulted = 0 

spot_df_new$End_Status <- ifelse(spot_df_new$End_Status == "resulted", 1, 0)

library(dplyr)

#t(t(names(spot_df_new)))

result_rates <- spot_df_new %>%
  group_by(Patient_ID, Type_of_Kit) %>%
  summarize(End_Status = mean(End_Status))

End_Status

```

```{r}
unique_status <- df %>%
  distinct(`Patient.ID`, `End.Status`)


df_filtered <- df %>%
  group_by(`Patient.ID`, `Type.of.Kit`, `Client.ID`) %>%
  filter(n_distinct(`End.Status`) > 1)
```

```{r}
# create a new df



new_df <- select (spot_df_new, Patient_ID, Type_of_Kit, End_Status)

new_df$End_Status <- ifelse(new_df$End_Status == "resulted", 1, 0)

result_rates <- new_df %>%
  group_by(Patient_ID,Type_of_Kit) %>%
  summarize(End_Status = sum(End_Status)/n())


```


```{r}
install.packages("sqldf")
library(sqldf)

df <- sqld("
           select id,
           ")


```



